
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    build:
      context: ./docker
    image: noctria-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__CORE__FERNET_KEY: "6LKqwTHAAeaA56VYt4BNLL236LhGagXYl2YMRzcXv3U="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /noctria-kingdom/airflow-docker/dags
      PYTHONPATH: /noctria-kingdom/airflow-docker
    volumes:
      - /mnt/e/noctria-kingdom-main/airflow-docker/dags:/noctria-kingdom/airflow-docker/dags
      - /mnt/e/noctria-kingdom-main/airflow-docker/logs:/noctria-kingdom/airflow-docker/logs
      - /mnt/e/noctria-kingdom-main/airflow-docker/plugins:/noctria-kingdom/airflow-docker/plugins
      - /mnt/e/noctria-kingdom-main/airflow-docker/scripts:/noctria-kingdom/airflow-docker/scripts
      - /mnt/e/noctria-kingdom-main/airflow-docker/core:/noctria-kingdom/airflow-docker/core
      - /mnt/e/noctria-kingdom-main/airflow-docker/strategies:/noctria-kingdom/airflow-docker/strategies
      - /mnt/e/noctria-kingdom-main/airflow-docker/data:/noctria-kingdom/airflow-docker/data
      - /mnt/e/noctria-kingdom-main/airflow-docker/models:/noctria-kingdom/airflow-docker/models
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  airflow-scheduler:
    build:
      context: ./docker
    image: noctria-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "6LKqwTHAAeaA56VYt4BNLL236LhGagXYl2YMRzcXv3U="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /noctria-kingdom/airflow-docker/dags
      PYTHONPATH: /noctria-kingdom/airflow-docker
    volumes:
      - /mnt/e/noctria-kingdom-main/airflow-docker/dags:/noctria-kingdom/airflow-docker/dags
      - /mnt/e/noctria-kingdom-main/airflow-docker/logs:/noctria-kingdom/airflow-docker/logs
      - /mnt/e/noctria-kingdom-main/airflow-docker/plugins:/noctria-kingdom/airflow-docker/plugins
      - /mnt/e/noctria-kingdom-main/airflow-docker/scripts:/noctria-kingdom/airflow-docker/scripts
      - /mnt/e/noctria-kingdom-main/airflow-docker/core:/noctria-kingdom/airflow-docker/core
      - /mnt/e/noctria-kingdom-main/airflow-docker/strategies:/noctria-kingdom/airflow-docker/strategies
      - /mnt/e/noctria-kingdom-main/airflow-docker/data:/noctria-kingdom/airflow-docker/data
      - /mnt/e/noctria-kingdom-main/airflow-docker/models:/noctria-kingdom/airflow-docker/models
    command: scheduler
    restart: always

volumes:
  postgres-db-volume:
