version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    build:
      context: ./docker
    image: noctria-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__CORE__FERNET_KEY: "6LKqwTHAAeaA56VYt4BNLL236LhGagXYl2YMRzcXv3U="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow:/opt/noctria
    volumes:
      - /mnt/e/noctria-kingdom-main/airflow-docker/dags:/opt/airflow/dags
      - /mnt/e/noctria-kingdom-main/airflow-docker/logs:/opt/airflow/logs
      - /mnt/e/noctria-kingdom-main/airflow-docker/plugins:/opt/airflow/plugins
      - /mnt/e/noctria-kingdom-main/airflow-docker/scripts:/opt/noctria/scripts
      - /mnt/e/noctria-kingdom-main/airflow-docker/core:/opt/noctria/core
      - /mnt/e/noctria-kingdom-main/airflow-docker/strategies:/opt/noctria/strategies
      - /mnt/e/noctria-kingdom-main/airflow-docker/data:/opt/airflow/data
      - /mnt/e/noctria-kingdom-main/airflow-docker/models:/opt/noctria/models
    ports:
      - "8080:8080"
    command: webserver
    restart: always

  airflow-scheduler:
    build:
      context: ./docker
    image: noctria-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "6LKqwTHAAeaA56VYt4BNLL236LhGagXYl2YMRzcXv3U="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow:/opt/noctria
    volumes:
      - /mnt/e/noctria-kingdom-main/airflow-docker/dags:/opt/airflow/dags
      - /mnt/e/noctria-kingdom-main/airflow-docker/logs:/opt/airflow/logs
      - /mnt/e/noctria-kingdom-main/airflow-docker/plugins:/opt/airflow/plugins
      - /mnt/e/noctria-kingdom-main/airflow-docker/scripts:/opt/noctria/scripts
      - /mnt/e/noctria-kingdom-main/airflow-docker/core:/opt/noctria/core
      - /mnt/e/noctria-kingdom-main/airflow-docker/strategies:/opt/noctria/strategies
      - /mnt/e/noctria-kingdom-main/airflow-docker/data:/opt/airflow/data
      - /mnt/e/noctria-kingdom-main/airflow-docker/models:/opt/noctria/models
    command: scheduler
    restart: always

volumes:
  postgres-db-volume:
