target-version = "py310"
line-length = 100

# ← セクション外（トップレベル）に置く
# 既存の除外に“追加”したい場合は extend-exclude を使ってOK
extend-exclude = [
  "_graveyard",
  "generated_code",
  "data",
  "airflow_docker",
  "noctria_gui",
  "llm_server",
  "tools",
  "scripts",
  "tests",
  "Untitled.ipynb",
]

[lint]
select = ["E", "F", "I", "W"]
ignore = []

[format]
line-length = 100
