target-version = "py310"
line-length = 100

# トップレベルで追加除外
extend-exclude = [
  "autogen_scripts",
  "mt5_test.py",
  "_graveyard",
  "generated_code",
  "data",
  "airflow_docker",
  "noctria_gui",
  "llm_server",
  "tools",
  "scripts",
  "tests",
  "Untitled.ipynb",
]

[lint]
select = ["E", "F", "W", "I"]
ignore = []

[format]
# ※ ここには line-length を置かない
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 100
