[tool.ruff]
extend = "ruff-baseline.toml"
target-version = "py311"
line-length = 100
src = ["src", "scripts", "tests", "noctria_gui"]

# 生成物や壊れている/デモ系を一旦除外（後で直して戻す）
exclude = [
  "src/codex_reports/**",
  "src/plan_data/kpi_minidemo.py",
  "scripts/_pdca_db.py",
  "src/codex/agents/proxy/tools/pytest_runner.py",
  "src/core/strategy_optimizer_adjusted.py",
  "src/tools/fix_import_paths.py",
]

[tool.ruff.lint]
# まずは致命系（E/F）＋ import整形（I）のみに絞る
select = ["E", "F", "I"]
ignore = [
  # 長行は一旦許容
  "E501",
]

[tool.ruff.lint.per-file-ignores]
# テストの * import は当面OK
"tests/*.py" = ["F403", "F405"]

# 学習/テンプレの * import
"src/scripts/meta_ai_tensorboard_train.py" = ["F403"]

# 一旦運用を止めたくない bare except
"src/tools/push_official_strategy_to_github.py" = ["E722"]

# GUI ルートの未定義参照はのちほど修復（現時点では許容してブロック回避）
"noctria_gui/routes/chat_api.py" = ["F821"]
"noctria_gui/routes/statistics_detail.py" = ["F821"]
"noctria_gui/routes/adoptions.py" = ["F841"]
"noctria_gui/services/dashboard_service.py" = ["F841"]
