FROM nvidia/cuda:12.2.0-cudnn8-runtime-ubuntu22.04

WORKDIR /opt/airflow
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/opt/airflow

COPY requirements.txt /tmp/
RUN apt update && apt install -y python3 python3-pip git \
 && pip3 install --upgrade pip \
 && pip3 install -r /tmp/requirements.txt

COPY . /opt/airflow
CMD ["bash"]
