# Noctria Kingdom のシステム設定
system:
  name: Noctria Kingdom
  version: 1.0.0
  description: "自律型FXトレーディングシステム"

logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"

strategies:
  trend_analysis: Aurus_Singularis
  scalping: Levia_Tempest
  risk_management: Noctus_Sentinella
  market_prediction: Prometheus_Oracle

market_settings:
  broker: "MetaTrader5"
  currency_pairs:
    - "EUR/USD"
    - "GBP/USD"
    - "USD/JPY"
  timeframe: "M15"

optimization:
  performance_tuning: true
  memory_management: true
  dynamic_strategy_tuning: true
  error_handling: true
