apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/airflow/dags  # ✅ KINDノード側にこのパスを mkdir しておくこと！

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow  # ✅ airflow-values.yaml の namespace と一致させる
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
