# airflow-docker/pvc/airflow-dags-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/e/noctria-kingdom-main/airflow-docker/dags"
