name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    # [skip ci] がコミットメッセージにあれば実行しない
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt. Skipping pip install."
          fi

      - name: Run tests
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests directory. Skipping tests."
          fi

      - name: Log in to DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_PASSWORD }}
        run: |
          set -euo pipefail
          REPO="${{ secrets.DOCKERHUB_USERNAME }}/noctria_trade_ai"
          TAG="${REPO}:$(date +'%Y%m%d%H%M%S')"
          docker build -t "$TAG" .
          docker push "$TAG"
