name: update_docs

on:
  push:
    # どのブランチでも、docs配下かスクリプトが変わったら走る
    branches:
      - '**'
    paths:
      - 'docs/**'
      - 'scripts/update_docs_from_index.py'
  # 手動実行も可（Actions > Run workflow）
  workflow_dispatch:

permissions:
  contents: write   # 変更をコミット＆プッシュするため

jobs:
  run-update-docs:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo   # JST表記の更新日時などに合わせたい場合
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # コミット差分やタグ参照が必要になる場合に備えて

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run update_docs_from_index.py
        run: |
          set -e
          if [ -f scripts/update_docs_from_index.py ]; then
            python scripts/update_docs_from_index.py
          else
            echo "scripts/update_docs_from_index.py が見つかりません。パスを確認してください。" >&2
            exit 1
          fi

      - name: Commit & push if changed
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "📄 AutoDoc: update docs from index [skip ci]"
            # 元のブランチにプッシュ
            git push
          else
            echo "ドキュメントの変更はありません。"
          fi
