name: update_docs

on:
  push:
    branches:
      - '**'                # どのブランチでも
    paths:
      - 'docs/**'           # docs配下の変更
      - 'scripts/update_docs_from_index.py'  # スクリプト更新
  workflow_dispatch:         # 手動実行も可

# ★ 同時実行をブランチごとに1本に固定（古い実行はキャンセル）
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write            # 変更をコミット＆プッシュするため

jobs:
  run-update-docs:
    # [skip ci] 付きコミットや bot 実行はスキップして再帰・ループ抑止
    if: contains(github.event.head_commit.message, '[skip ci]') == false && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Tokyo         # JST表記が必要なら

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Install ripgrep (for sanity checks)
        run: |
          set -euo pipefail
          sudo apt-get -yqq update
          sudo apt-get -yqq install ripgrep

      - name: Run update_docs_from_index.py
        run: |
          set -euo pipefail
          if [ -f scripts/update_docs_from_index.py ]; then
            python scripts/update_docs_from_index.py
          else
            echo "scripts/update_docs_from_index.py が見つかりません。パスを確認してください。" >&2
            exit 1
          fi

      - name: Docs sanity check
        run: |
          set -euo pipefail
          # 1) 連続 AUTODOC マーカーがないか
          if rg -nUP '(<!-- AUTODOC:(?:BEGIN|END)[^>]*-->[ \t]*\R){2,}' docs -g '!docs/_generated/**' ; then
            echo "ERROR: consecutive AUTODOC markers found"
            exit 1
          fi
          # 2) diff 断片が混入していないか
          if rg -n "(@@ -[0-9]+,[0-9]+ \+[0-9]+,[0-9]+ @@|^diff --git|^index [0-9a-f]{7,}\.\.)" docs -g '!docs/_generated/**' ; then
            echo "ERROR: stray diff hunks found"
            exit 1
          fi

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            # 他ワークフロー（Buildなど）を走らせないための目印
            git commit -m "📄 AutoDoc: update docs from index [skip ci]"
            git push
          else
            echo "ドキュメントの変更はありません。"
          fi
