# Airflow Helm Chart values
# 公式: https://github.com/apache/airflow/tree/main/chart

executor: CeleryExecutor

# Airflow イメージ
images:
  airflow:
    repository: apache/airflow
    tag: 2.7.3  # ✅ 安定版に変更
    pullPolicy: IfNotPresent

# DAGsマウント設定（persistence経由）
dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc  # PVCは別途作成
    subPath: ""  # サブディレクトリなしで直下マウント
  gitSync:
    enabled: false  # Git連携は一旦使わない

# logs（persistenceでPVCマウントも可能）
logs:
  persistence:
    enabled: false  # 必要ならtrueにしてPVC設定追加

# Webサーバー設定
webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin  # セキュリティの都合であとで変更推奨
  service:
    type: ClusterIP

# ✅ 静的なWebserver Secret Keyの設定（警告抑制）
webserverSecretKey:
  secretName: airflow-webserver-secret-key
  secretKey: UJ7lYMq8DoWzNRuRkQRvpxw3JVgkoDFgRLEK0750xW00vt7DQKF72erikMJfPrDwaQGG9pqkOg1UYn6g-IRi7g

# PostgreSQL（新方式）
postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

# Redis (CeleryExecutor用)
redis:
  enabled: true
  password: ""

# Kubernetes executor/pod template (KPOなど使う場合)
kubernetesPodTemplate:
  enabled: false  # trueにして pod_template.yaml を使うことも可能

# Workerリソース制限（任意で調整）
workers:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# flower UI
flower:
  enabled: false
