executor: CeleryExecutor

images:
  airflow:
    repository: noctria/airflow-custom  # ✅ カスタムイメージを指定
    tag: 2.9.1
    pullPolicy: IfNotPresent

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc
    subPath: ""  # 直下にマウント
  gitSync:
    enabled: false  # Git連携は一旦無効

logs:
  persistence:
    enabled: false  # 任意で true に（PVC作成が必要）

webserver:
  defaultUser:
    enabled: true  # 任意（falseでもOKだが、enabledならhook失敗対策が必要）
    username: admin
    password: admin
  service:
    type: ClusterIP

webserverSecretKey: UJ7lYMq8DoWzNRuRkQRvpxw3JVgkoDFgRLEK0750xW00vt7DQKF72erikMJfPrDwaQGG9pqkOg1UYn6g-IRi7g

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: true
  password: ""

kubernetesPodTemplate:
  enabled: false

workers:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

flower:
  enabled: false

# ✅ create-user ジョブを無効化（fab系モジュールエラー回避）
createUserJob:
  enabled: false
