executor: CeleryExecutor

images:
  airflow:
    repository: noctria/airflow-custom
    tag: 2.9.1
    pullPolicy: IfNotPresent

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc
    subPath: ""
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: false

webserver:
  defaultUser:
    enabled: false  # ✅ create-user job 無効化
  service:
    type: ClusterIP
  persistence:
    dags:
      enabled: true
      existingClaim: airflow-dags-pvc

scheduler:
  persistence:
    dags:
      enabled: true
      existingClaim: airflow-dags-pvc

workers:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  persistence:
    dags:
      enabled: true
      existingClaim: airflow-dags-pvc

webserverSecretKey: UJ7lYMq8DoWzNRuRkQRvpxw3JVgkoDFgRLEK0750xW00vt7DQKF72erikMJfPrDwaQGG9pqkOg1UYn6g-IRi7g

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: true
  password: ""

kubernetesPodTemplate:
  enabled: false

flower:
  enabled: false
