name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker images
        run: |
          docker build -t your_registry/noctria-backend ./backend
          docker build -t your_registry/noctria-frontend ./frontend
      
      - name: Push Docker images
        run: |
          docker push your_registry/noctria-backend
          docker push your_registry/noctria-frontend
      # ここに自動デプロイのステップを追加（例：kubectl apply ...）
