name: Airflow Backtest on Adopt PR Merge

on:
  pull_request:
    types: [closed]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trigger-backtest:
    # adopt/* のマージ時 or 手動実行で動作
    if: >
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       startsWith(github.event.pull_request.head.ref, 'adopt/'))
      || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (merged commit or default)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.ref }}

      - name: Trigger Airflow Backtest DAG (Basic Auth)
        env:
          AIRFLOW_BASE_URL:        ${{ secrets.AIRFLOW_BASE_URL }}          # 例: https://xxxx.trycloudflare.com
          AIRFLOW_BASIC_B64:       ${{ secrets.AIRFLOW_BASIC_B64 }}         # base64("admin:admin") など
          AIRFLOW_BACKTEST_DAG_ID: ${{ vars.AIRFLOW_BACKTEST_DAG_ID }}      # 例: noctria_kingdom_pdca_dag

          # メタ情報（PR/手動どちらでも埋まる）
          PR_TITLE:  ${{ github.event.pull_request.title        || 'manual-trigger' }}
          PR_NUMBER: ${{ github.event.pull_request.number       || 'manual' }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref     || github.ref_name }}
          PR_MERGER: ${{ github.event.pull_request.merged_by.login || github.actor }}
          REPO:      ${{ github.repository }}
          SHA:       ${{ github.event.pull_request.merge_commit_sha || github.sha }}
        run: |
          set -euo pipefail
          if [ -z "${AIRFLOW_BASE_URL:-}" ] || [ -z "${AIRFLOW_BASIC_B64:-}" ] || [ -z "${AIRFLOW_BACKTEST_DAG_ID:-}" ]; then
            echo "Missing AIRFLOW_BASE_URL / AIRFLOW_BASIC_B64 / AIRFLOW_BACKTEST_DAG_ID" >&2
            exit 1
          fi

          BASE="${AIRFLOW_BASE_URL%/}"
          DAG_RUN_ID="pr-${PR_NUMBER}-${SHA:0:7}"
          BODY='{"dag_run_id":"'"${DAG_RUN_ID}"'","conf":{"repo":"'"${REPO}"'","pr":"'"${PR_NUMBER}"'","branch":"'"${PR_BRANCH}"'","title":"'"${PR_TITLE}"'","sha":"'"${SHA}"'","merger":"'"${PR_MERGER}"'"}}'

          echo "POST ${BASE}/api/v1/dags/${AIRFLOW_BACKTEST_DAG_ID}/dagRuns"
          http_code=$(
            curl -sS -o /tmp/airflow_resp.json -w '%{http_code}' \
              -X POST "${BASE}/api/v1/dags/${AIRFLOW_BACKTEST_DAG_ID}/dagRuns" \
              -H "Authorization: Basic ${AIRFLOW_BASIC_B64}" \
              -H "Content-Type: application/json" \
              --data "${BODY}"
          )
          echo "Airflow response code: ${http_code}"
          cat /tmp/airflow_resp.json || true
          case "${http_code}" in 2*) exit 0 ;; *) exit 1 ;; esac
