name: smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest (smoke only)
        run: pytest -q tests/smoke
