name: ci-smoke

on:
  push:
    branches: [ main, "fix/**", "feature/**", "chore/**" ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps (best-effort)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install ruff pytest

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest (smoke only)
        run: pytest -q tests/smoke
