name: Inventor Decision Guard (PR only)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]
    paths:
      - "**.py"
      - "tests/**"
      - "scripts/**"
      - "pytest.ini"
      - ".github/workflows/**"
      - "airflow_docker/dags/**"
      - "airflow_docker/scripts/show_last_inventor_decision.py"
      - "airflow_docker/codex_reports/inventor_last.json"

concurrency:
  group: inventor-guard-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run smoke tests
        run: |
          pytest -q tests/test_decision_fallback_size.py
