name: Inventor Decision Guard (PR only)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "airflow_docker/dags/**"
      - "airflow_docker/scripts/show_last_inventor_decision.py"
      - "airflow_docker/codex_reports/inventor_last.json"
      - ".github/workflows/inventor-pr-guard.yml"

concurrency:
  group: inventor-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assert-decision-size:
    name: Assert decision.size > 0 (if artifact present)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show context
        run: |
          echo "PR: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.head_ref || github.ref_name }}"
          echo "Repo: ${{ github.repository }}"

      - name: Check artifact presence
        id: check_artifact
        run: |
          ART="airflow_docker/codex_reports/inventor_last.json"
          if [ -f "$ART" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "::notice::Found $ART in repo."
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "::notice::No $ART found. This job will skip with success."
          fi

      - name: Assert decision.size > 0
        if: steps.check_artifact.outputs.found == 'true'
        run: |
          python - <<'PY'
          import json, sys, pathlib
          p = pathlib.Path("airflow_docker/codex_reports/inventor_last.json")
          data = json.loads(p.read_text(encoding="utf-8"))
          dec = (data.get("decision") or {})
          size = float(dec.get("size", 0) or 0)
          if size <= 0:
              print("ASSERTION FAILED: decision.size <= 0")
              print(json.dumps(data, ensure_ascii=False, indent=2))
              sys.exit(1)
          print("OK: decision.size =", size)
          print(json.dumps(data, ensure_ascii=False, indent=2))
          PY

      - name: Soft-skip when artifact missing
        if: steps.check_artifact.outputs.found != 'true'
        run: |
          echo "::notice::Skipping assertion because artifact is not in the PR."
          echo "Tip: Commit airflow_docker/codex_reports/inventor_last.json from your Airflow run if you want this check to enforce size>0."
