name: lint

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install ruff
        run: pip install "ruff==0.6.8"

      - name: Lint (ruff check)
        run: ruff check --force-exclude src/core

      - name: Format check (ruff format --check)
        run: ruff format --check --force-exclude src/core
