name: lint

on:
  push:
    branches: ["**"]
    paths:
      - "src/core/**"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "src/core/**"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"

jobs:
  ruff:
    # ← Branch protection では「lint / ruff」と表示される
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --force-exclude src/core

  ruff-format:
    # ← Branch protection では「lint / ruff-format」と表示される
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --force-exclude src/core
