# .github/workflows/lint.yml
name: lint

on:
  push:
    branches: ["**"]
    paths:
      - "src/core/**"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "src/core/**"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"

jobs:
  ruff:
    # Branch protection 上では「lint / ruff」と表示される
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          # ローカル(pre-commit)と揃えるためにバージョン固定
          version: "0.6.8"
          # PR にアノテーションを出すため --output-format=github を追加
          args: check --force-exclude src/core --output-format=github

  ruff-format:
    # Branch protection 上では「lint / ruff-format」と表示される
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.6.8"
          args: format --check --force-exclude src/core
