name: noctria_policy_check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pyyaml
      - name: Validate codex policy YAML
        run: |
          python - <<'PY'
          import yaml
          yaml.safe_load(open("docs/codex/codex_noctria_policy.yaml","r",encoding="utf-8"))
          print("policy ok")
          PY
      - name: Block bot direct-to-main
        run: |
          PR_TARGET="${{ github.base_ref }}"
          PR_ACTOR="${{ github.actor }}"
          if [[ "$PR_ACTOR" == "inventor-scriptus-bot" && "$PR_TARGET" == "main" ]]; then
            echo "Inventor Scriptus cannot target main directly."
            exit 1
          fi
