name: PR — Inventor Guard (light tests)
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pytest.ini'
      - '.github/workflows/pr-inventor-guard.yml'
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          # ここは軽量依存だけでOK（numpy/pydantic など必要に応じて追加）
          pip install pytest

      - name: Run unit tests (light)
        run: |
          pytest -q
