name: runner-smoke
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/runner-smoke.yml"

jobs:
  smoke:
    runs-on: [self-hosted, Linux, X64]  # 追加ラベルを使うなら [self-hosted, wsl2, py312]
    steps:
      - uses: actions/checkout@v4
      - name: Show runner info
        run: |
          echo "uname: $(uname -a)"
          echo "whoami: $(whoami)"
      - name: Python check
        run: |
          command -v python3 || true
          python3 --version || true
